### ISSUE TITLE
Bug with deleting characters on mobile

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/ds-character-count#1]
When deleting characters on mobile, something seems to go wrong with spacing - once the last character is deleted, the carat appears too far to the left.

![charcount-mobile-delete-bug](https://user-images.githubusercontent.com/2204224/33181606-bf6d9142-d068-11e7-9cf7-5d4b312dc745.gif)

**Comment by alex-ju** [comment]
Sorry for the late reply.
Fixed and updated the [heroku deployment](https://govuk-charcount-prototype.herokuapp.com).
Thanks for reporting this @edwardhorsford!
